# Generated by Django 3.0.7 on 2020-08-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='CEP')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
            ],
            options={
                'verbose_name': 'Index',
                'verbose_name_plural': 'Indexes',
            },
        ),
    ]
