# Generated by Django 3.0.7 on 2020-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapmodel',
            name='birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nascimento do beneficiário'),
        ),
        migrations.AddField(
            model_name='scrapmodel',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do beneficiário'),
        ),
        migrations.AddField(
            model_name='scrapmodel',
            name='medical_records_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do prontuário'),
        ),
        migrations.AddField(
            model_name='scrapmodel',
            name='medical_records_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número do prontuário'),
        ),
        migrations.AlterField(
            model_name='scrapmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do beneficiário'),
        ),
    ]
