# Generated by Django 3.0.7 on 2020-08-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200810_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapmodel',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link prontuário'),
        ),
    ]
