# Generated by Django 3.0.7 on 2020-08-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scrapmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapmodel',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link prontuário'),
        ),
    ]
