# Generated by Django 3.1 on 2020-08-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200811_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapmodel',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='scrapmodel',
            name='medical_records_date',
        ),
        migrations.RemoveField(
            model_name='scrapmodel',
            name='professional_code',
        ),
        migrations.RemoveField(
            model_name='scrapmodel',
            name='professional_name',
        ),
        migrations.AddField(
            model_name='scrapmodel',
            name='attendance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do atendimento'),
        ),
        migrations.AddField(
            model_name='scrapmodel',
            name='date_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de entrada'),
        ),
        migrations.AddField(
            model_name='scrapmodel',
            name='health_insurance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do convênio'),
        ),
        migrations.AddField(
            model_name='scrapmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do(a) beneficiário(a)'),
        ),
        migrations.AddField(
            model_name='scrapmodel',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='scrapmodel',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=10, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='scrapmodel',
            name='uti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do leito'),
        ),
    ]
