# Generated by Django 3.1 on 2020-08-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200814_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapmodel',
            old_name='attendance',
            new_name='attendance_number',
        ),
    ]
