# Generated by Django 3.1 on 2020-08-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200814_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapmodel',
            name='filename',
            field=models.CharField(default='qualquer nome', max_length=255, verbose_name='Nome doarquivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrapmodel',
            name='sex',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10, null=True, verbose_name='Sexo'),
        ),
    ]
