# Generated by Django 3.1 on 2020-08-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200814_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapmodel',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='Nome do arquivo'),
        ),
    ]
