# Generated by Django 3.1 on 2020-08-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200814_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapModel',
            new_name='IndexedFileModel',
        ),
    ]
